/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    ConsolidatedIndicators: typeof import('./src/components/ConsolidatedIndicators/ConsolidatedIndicators.vue')['default']
    IBiArrowBarLeft: typeof import('~icons/bi/arrow-bar-left')['default']
    IBiArrowBarRight: typeof import('~icons/bi/arrow-bar-right')['default']
    IBiCashCoin: typeof import('~icons/bi/cash-coin')['default']
    IBiCellphoneScreenshotTwotone: typeof import('~icons/bi/cellphone-screenshot-twotone')['default']
    IBiCloudDownload: typeof import('~icons/bi/cloud-download')['default']
    IBiCurrencyDollar: typeof import('~icons/bi/currency-dollar')['default']
    IBiDollar: typeof import('~icons/bi/dollar')['default']
    IBiScreenshot: typeof import('~icons/bi/screenshot')['default']
    IBiScreenshot2Fill: typeof import('~icons/bi/screenshot2-fill')['default']
    IBiTaxiFront: typeof import('~icons/bi/taxi-front')['default']
    IconCustom: typeof import('./src/components/IconCustom/IconCustom.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    Profile: typeof import('./src/components/Profile/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextIndicators: typeof import('./src/components/TextIndicators/TextIndicators.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
  }
}
